---
# NOTICE: As required by the Apache License v2.0, this notice is to state this file has been modified by Arachne Digital
# This file has been moved into a different directory
# To see its full history, please use `git log --follow <filename>` to view previous commits and additional contributors

# The following fields must have a value.
# If any of these fields are omitted at runtime, they will default to their original values.

# Specified host and port where Thread will run
host: 0.0.0.0
port: 9999
# If you are running Thread locally (you may want to set as True to bypass user restrictions locally)
run-local: True
# Either 'taxii-server' for latest data or 'local-json' to use local data (data from json_file)
taxii-local: taxii-server
# Either 'js-online-src' for fetching JS libraries online or 'js-local-src' to use locally saved JS libraries
js-libraries: js-online-src
# The database backend to use: currently either 'sqlite3' or 'postgresql' (sqlite3 recommended for local-use)
# If using postgresql, requires package psycopg2 (see pre-reqs: https://www.psycopg.org/docs/install.html#prerequisites)
# If not using postgresql, you can (re)move the file database/thread_postgresql.py to avoid installing psycopg2
db-engine: sqlite3
# If you would like the database to be re-built on launch of Thread
# Ineffective when db-engine = 'postgresql'; if wanted, call `main.py --build-db` separately (before launching Thread)
build: True
# The maximum number of reports which can be analysed concurrently at a time.
# The default value of 1 means for reports in the queue, one is analysed at a time before the next report in the queue.
max-analysis-tasks: 1

# The following fields are optional - please check comments for behaviour when omitted.

# The JSON file containing attack data; ensure file is in /models directory
# MUST BE SET if taxii-local = 'local-json'
json_file: enterprise-attack.json
# The maximum number of reports allowed in the queue; for no limit, remove this field or set value x < 1
queue_limit: 20
